# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plan', '0002_auto_20160826_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_user', to='login_reg.User'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_create', to='login_reg.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
