# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
